### ISSUE TITLE
[BUG] Gallery-Connector image passthru does not work!?

### ISSUE THREAD

**Issue by thehe** [splittingred/Gallery#60]
hey guys,

on my configuration the connector only creates the picture but does not serve it correctly to the client - only on the second request the image is correctly delivered from cache!

After hours of debugging in the output-buffered and encapsulated processors i just figured out that it should work!
the 'RedirectToCachedFile'-Method in galPhpThumb is responsible for both, the "create thumb and serve" and "serve thumb from cache"-functions, called exactly the same way...

i have no idea to fix it...

kind regards,
Robin

**Comment by thehe** [comment]
if ($getimagesize) {
                header('Content-Type: '.phpthumb_functions::ImageTypeToMIMEtype($getimagesize[2]));
            } elseif (eregi('.ico$', $this->cache_filename)) {
                header('Content-Type: image/x-icon');
            }
            if (!$this->config_cache_force_passthru && ereg('^'.preg_quote($nice_docroot).'(.*)$', $nice_cachefile, $matches)) {
                header('Location: '.dirname($matches[1]).'/'.urlencode(basename($matches[1])));
            } else {
                $ret = file_get_contents($this->cache_filename);
                echo $ret;
                return $ret;
                //@readfile($this->cache_filename);
            }

 ^^ problem was the readfile! the request-handler wants a return value from the processor which calls "modphpthumb.class.php"...

**Comment by splittingred** [comment]
Fixed: https://github.com/splittingred/Gallery/commit/586239ab8a6e3dbedd75f2073b26bd4172d3a5de

Thanks!

**Comment by thehe** [comment]
Dear Team,

same Bug still exists in modPhpThumb-Class...

Who gives it to the ModX-Team?

Greetings,

Robin

-----Ursprüngliche Nachricht-----
Von: splittingred [mailto:reply@reply.github.com] 
Gesendet: Freitag, 11. März 2011 15:30
An: Robin Parker
Betreff: Re: [GitHub] [BUG] Gallery-Connector image passthru does not work!? [splittingred/Gallery GH-60]

Fixed: https://github.com/splittingred/Gallery/commit/586239ab8a6e3dbedd75f2073b26bd4172d3a5de

Thanks!

https://github.com/splittingred/Gallery/issues/60#comment_860650
